#!/usr/bin/env bash

# Configure Bash to print commands, exit on errors, and propagate pipeline failures.
set -euxo pipefail

# See [ref:integration_test_step] for how to run this integration test.

# Wait for the Docker daemon to start up.
echo 'Waiting for Docker to start…'
while ! docker container ls > /dev/null 2>&1; do
  sleep 1
done

# Configure the temporary build context and image names used by the test.
BUILD_CONTEXT_DIR="$(mktemp -d)"
LOG_FILE="$(mktemp)"
IMAGE_SIZE_BYTES=104857600
EVICTION_MARGIN_BYTES=200000000
PROTECTED_IMAGE=docuum-test-keep
EVICTED_IMAGE=docuum-test-evict
LATEST_IMAGE=docuum-test-latest

# Write the Dockerfile used to create scratch images with a single payload layer.
cat > "$BUILD_CONTEXT_DIR/Dockerfile" <<'EOF'
FROM scratch
COPY payload /payload
EOF

# This will be called when the test finishes, regardless of whether it succeeded.
cleanup() {
  # Stop Docuum if it was started.
  if [[ -n "${DOCUUM_PID:-}" ]]; then
    echo 'Killing Docuum…'
    kill "$DOCUUM_PID" 2> /dev/null || true
  fi

  # Print Docuum's log if it was created.
  if [[ -f "$LOG_FILE" ]]; then
    echo 'Docuum log:'
    cat "$LOG_FILE"
  fi

  # Delete the temporary build context.
  rm -rf "$BUILD_CONTEXT_DIR"
}

# Run the cleanup function on exit.
trap cleanup EXIT

# Build a test image with a fresh random payload.
build_test_image() {
  local IMAGE="$1"

  # Regenerate the payload so Docker cannot deduplicate layers across test images.
  echo "Building $IMAGE…"
  head -c "$IMAGE_SIZE_BYTES" /dev/urandom > "$BUILD_CONTEXT_DIR/payload"
  docker image build --no-cache --tag "$IMAGE" "$BUILD_CONTEXT_DIR"
}

# Print Docker's current image space usage in bytes.
image_space_bytes() {
  # Parse the human-readable image size reported by `docker system df`.
  docker system df --format '{{.Type}}\t{{.Size}}' | awk '
    $1 == "Images" {
      SIZE = $2
      if (SIZE ~ /kB$/) {
        MULTIPLIER = 1000
        sub(/kB$/, "", SIZE)
      } else if (SIZE ~ /MB$/) {
        MULTIPLIER = 1000000
        sub(/MB$/, "", SIZE)
      } else if (SIZE ~ /GB$/) {
        MULTIPLIER = 1000000000
        sub(/GB$/, "", SIZE)
      } else if (SIZE ~ /B$/) {
        MULTIPLIER = 1
        sub(/B$/, "", SIZE)
      } else {
        exit 1
      }

      printf "%.0f\n", SIZE * MULTIPLIER
    }
  '
}

# Build the protected and evictable images before Docuum starts so the initial vacuum sees both. Each
# test image contains a unique 100 MiB layer. We derive the threshold from Docker's own image space
# accounting after these two builds, then add a margin so the initial vacuum stays below the
# threshold but one more image still pushes us over it. The margin leaves room for BuildKit's
# provenance and cache accounting.
build_test_image "$PROTECTED_IMAGE"
build_test_image "$EVICTED_IMAGE"

# Set the threshold just above Docker's current image space usage.
THRESHOLD_BYTES="$(($(image_space_bytes) + EVICTION_MARGIN_BYTES))"
echo "Using a threshold of $THRESHOLD_BYTES bytes…"

# Start Docuum in the background, capturing its output in a log file. Trace-level logging is
# needed because the synchronization logic below relies on Docuum logging each incoming event.
echo 'Starting Docuum…'
LOG_LEVEL=trace /docuum-x86_64-unknown-linux-musl --threshold "$THRESHOLD_BYTES B" \
  --keep "$PROTECTED_IMAGE:latest" \
  > "$LOG_FILE" 2>&1 &
DOCUUM_PID="$!"

# This function waits for Docuum to finish processing the events generated by the Docker commands
# run so far. It emits a sentinel event by creating and removing a Docker network with a unique
# name, then waits for Docuum to log that it received an event mentioning that name
# [ref:incoming_event]. Docker delivers events to subscribers in order and Docuum processes them
# sequentially, so once Docuum has received the sentinel event, all earlier events have been fully
# processed. Network events are irrelevant to Docuum, so the sentinel itself has no effect on its
# state.
SENTINEL_INDEX=0
wait_for_docuum() {
  # Emit a sentinel network event.
  echo 'Waiting for Docuum to process events…'
  SENTINEL_INDEX="$((SENTINEL_INDEX + 1))"
  docker network create "docuum-sentinel-$SENTINEL_INDEX" > /dev/null
  docker network rm "docuum-sentinel-$SENTINEL_INDEX" > /dev/null

  # Wait until Docuum has received the sentinel event.
  while ! grep -q "docuum-sentinel-$SENTINEL_INDEX" "$LOG_FILE"; do
    sleep 1
  done
}

# This function waits for Docuum to finish its initial vacuum and start listening for events
# [ref:listening_for_docker_events]. Docuum subscribes to events by spawning the Docker CLI, which
# establishes the subscription asynchronously, so we then repeatedly emit sentinel events until
# Docuum reports receiving one. This proves the subscription is live and no subsequent events will
# be missed.
wait_for_docuum_to_start() {
  # Wait until Docuum has spawned the Docker events command.
  echo 'Waiting for Docuum to start listening for events…'
  while ! grep -q 'Listening for Docker events' "$LOG_FILE"; do
    sleep 1
  done

  # Emit probe events until Docuum proves its event subscription is live.
  echo 'Waiting for the event subscription to be established…'
  local PROBE_INDEX=0
  while ! grep -q 'docuum-probe-' "$LOG_FILE"; do
    PROBE_INDEX="$((PROBE_INDEX + 1))"
    docker network create "docuum-probe-$PROBE_INDEX" > /dev/null
    docker network rm "docuum-probe-$PROBE_INDEX" > /dev/null
    sleep 1
  done
}

# Wait for Docuum to complete its startup work before emitting test events.
wait_for_docuum_to_start

# Assert that the first non-protected image is still present before the threshold has been exceeded.
echo 'Checking that the first non-protected image is still present…'
docker image inspect "$EVICTED_IMAGE" > /dev/null 2>&1

# Build the latest image after Docuum is listening so the build emits events Docuum must process.
build_test_image "$LATEST_IMAGE"

# Wait for Docuum to process the latest image build events.
wait_for_docuum

# Assert that the image protected by the `--keep` flag is still present.
echo 'Checking that the protected image is still present…'
docker image inspect "$PROTECTED_IMAGE" > /dev/null 2>&1

# Assert that the last image is still present.
echo 'Checking that the last image is still present…'
docker image inspect "$LATEST_IMAGE" > /dev/null 2>&1

# Assert that the first non-protected image was deleted.
echo 'Checking that the first non-protected image was deleted…'
if docker image inspect "$EVICTED_IMAGE" > /dev/null 2>&1
then
  echo "The image wasn't deleted."
  exit 1
fi
