#!/usr/bin/env bash
set -euxo pipefail

# See [ref:integration_test_step] for how to run this integration test.

# Wait for the Docker daemon to start up.
echo 'Waiting for Docker to start…'
while ! docker container ls > /dev/null 2>&1; do
  sleep 1
done

# Start Docuum in the background, capturing its output in a log file. Trace-level logging is
# needed because the synchronization logic below relies on Docuum logging each incoming event.
echo 'Starting Docuum…'
LOG_FILE="$(mktemp)"
LOG_LEVEL=trace /docuum-x86_64-unknown-linux-musl --threshold '20 MB' --keep 'alpine:keep' \
  > "$LOG_FILE" 2>&1 &
DOCUUM_PID="$!"

# This will be called when the test finishes, regardless of whether it succeeded.
cleanup() {
  echo 'Killing Docuum…'
  kill "$DOCUUM_PID" 2> /dev/null || true

  echo 'Docuum log:'
  cat "$LOG_FILE"
}
trap cleanup EXIT

# This function waits for Docuum to finish processing the events generated by the Docker commands
# run so far. It emits a sentinel event by creating and removing a Docker network with a unique
# name, then waits for Docuum to log that it received an event mentioning that name
# [ref:incoming_event]. Docker delivers events to subscribers in order and Docuum processes them
# sequentially, so once Docuum has received the sentinel event, all earlier events have been fully
# processed. Network events are irrelevant to Docuum, so the sentinel itself has no effect on its
# state.
SENTINEL_INDEX=0
wait_for_docuum() {
  echo 'Waiting for Docuum to process events…'
  SENTINEL_INDEX="$((SENTINEL_INDEX + 1))"
  docker network create "docuum-sentinel-$SENTINEL_INDEX" > /dev/null
  docker network rm "docuum-sentinel-$SENTINEL_INDEX" > /dev/null
  while ! grep -q "docuum-sentinel-$SENTINEL_INDEX" "$LOG_FILE"; do
    sleep 1
  done
}

# This function waits for Docuum to finish its initial vacuum and start listening for events
# [ref:listening_for_docker_events]. Docuum subscribes to events by spawning the Docker CLI, which
# establishes the subscription asynchronously, so we then repeatedly emit sentinel events until
# Docuum reports receiving one. This proves the subscription is live and no subsequent events will
# be missed.
wait_for_docuum_to_start() {
  echo 'Waiting for Docuum to start listening for events…'
  while ! grep -q 'Listening for Docker events' "$LOG_FILE"; do
    sleep 1
  done

  echo 'Waiting for the event subscription to be established…'
  local probe_index=0
  while ! grep -q 'docuum-probe-' "$LOG_FILE"; do
    probe_index="$((probe_index + 1))"
    docker network create "docuum-probe-$probe_index" > /dev/null
    docker network rm "docuum-probe-$probe_index" > /dev/null
    sleep 1
  done
}

wait_for_docuum_to_start

# This image uses ~5.5 MB. We remove the container explicitly rather than using `--rm` because
# `--rm` removes the container asynchronously, which would allow the resulting events to arrive
# after the sentinel event emitted by `wait_for_docuum`.
echo "Using an image we don't want to delete…"
docker container run --name docuum-test-1 \
  alpine@sha256:f27cad9117495d32d067133afff942cb2dc745dfe9163e949f6bfe8a6a245339 true
docker container rm docuum-test-1
docker image tag alpine@sha256:f27cad9117495d32d067133afff942cb2dc745dfe9163e949f6bfe8a6a245339 \
  alpine:keep

wait_for_docuum

# This image also uses ~5.5 MB.
echo 'Using another image…'
docker container run --name docuum-test-2 \
  alpine@sha256:2039be0c5ec6ce8566809626a252c930216a92109c043f282504accb5ee3c0c6 true
docker container rm docuum-test-2

wait_for_docuum

# This image also uses ~5.5 MB. For some reason, this pushes us over the 20 MB
# threshold, even though we've only downloaded ~5.5 MB * 3 = ~16.5 MB.
echo 'Using another image…'
docker container run --name docuum-test-3 \
  alpine@sha256:4d889c14e7d5a73929ab00be2ef8ff22437e7cbc545931e52554a7b00e123d8b true
docker container rm docuum-test-3

wait_for_docuum

# Assert that the image protected by the `--keep` flag is still present.
echo 'Checking that the protected image is still present…'
docker image inspect alpine@sha256:f27cad9117495d32d067133afff942cb2dc745dfe9163e949f6bfe8a6a245339 > \
  /dev/null 2>&1

# Assert that the last image is still present.
echo 'Checking that the last image is still present…'
docker image inspect alpine@sha256:4d889c14e7d5a73929ab00be2ef8ff22437e7cbc545931e52554a7b00e123d8b > \
  /dev/null 2>&1

# Assert that the first non-protected image was deleted.
echo 'Checking that the first non-protected image was deleted…'
if docker image inspect alpine@sha256:2039be0c5ec6ce8566809626a252c930216a92109c043f282504accb5ee3c0c6 \
  > /dev/null 2>&1
then
  echo "The image wasn't deleted."
  exit 1
fi
